---
# Install packages on a redhat family distribution.

- name: Add the Elasticsearch RPM key.
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add the Elasticsearch repository.
  yum_repository:
    name: Elasticsearch repository
    description: Elasticsearch repository for 5.x packages.
    baseurl: https://packages.elastic.co/elasticsearch/5.x/centos
    gpgcheck: yes
    enabled: yes

- name: Install elasticsearch.
  yum: name=elasticsearch state=latest
   
- name: Configure Elasticsearch.
  include: elasticsearch.yml